### ISSUE TITLE
Migrate website content and style to github pages.

### ISSUE THREAD

**Issue by simonsasse** [seqan/www.seqan.de#58]
### Description 

Migrate the website to github pages.
The current state: https://github.com/marehr/www.seqan.de/
The original website: www.seqan.de

### Benefits

- security
- speed
- maintenance 

### Tasks

- [x] basic framework (https://github.com/marehr/www.seqan.de/)
- [x] peoples page mechanics.
- [x] People's pages
- [x] Posts/news
- [x] application page mechanics.
- [x] Applications
- [x] publications page mechanics
- [x] Publications
- [x] create subpages for links on home (data structures, workflows, parrallelization, i/o, apps, workflows)
- [x] make people, applications and publications collapsible or add sub pages
- [x] redirect domain to github page
- [x] Automatically fetch http://publications.imp.fu-berlin.de/view/divisions/group=5Falgbioinf.html bibtex and generate publication site.

## Preprocessing of publications file using github actions:
- [x] Downlaod publication.json and publications.bib( http://publications.imp.fu-berlin.de/cgi/exportview/divisions/group=5Falgbioinf/JSON/group=5Falgbioinf.js )
- [x] convert to .yml using bitexparser in python.

### People page:
- [x] move avatar into summary
- [x] remove collapsibility of categories
- [x] fallback for no bio and so on.
